/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package employeedb;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
public class EmployeeSearching extends javax.swing.JDialog {
    
        Connection con = null;
        Statement ste  = null;
        ResultSet rs = null;
   
    public EmployeeSearching(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try{
            con = clsDBConnection.getConnection();
            fillRecord("Select * from Employee order by EmployeeID");
        }
        catch(Exception sqle)
        {
            System.out.println(sqle);
        }
        
    }
    
    
    public void fillRecord(String sql)
    {
        try
        {
            ste = con.createStatement();

            javax.swing.table.DefaultTableModel dtmModel = new DefaultTableModel();
            dtmModel.addColumn("Employee ID");
            dtmModel.addColumn("Employee Name");
            dtmModel.addColumn("NRC NO");
            dtmModel.addColumn("Gender");
            dtmModel.addColumn("Employee Address");
            dtmModel.addColumn("Department");
            dtmModel.addColumn("Post");
            dtmModel.addColumn("Qualification");
            //String sql = "Select * from Employee order by EmployeeID";
            
            rs = ste.executeQuery(sql);
            
            while(rs.next())
            {
                Object []dataRow = new Object[8] ;
                dataRow[0] = rs.getInt(1);
                
                for (int i = 2; i<= 8; i++)
                {
                   dataRow[i-1] = rs.getString(i);
                }
                dtmModel.addRow(dataRow);
            }
            tblEmployee.setModel(dtmModel);
            
            

            }
            
        
        catch(SQLException sqle)
        {
            System.out.println(sqle);
        }
    }
    
    public void fillSearchData(String sql)
    {
        
        if(!sql.equals(""))
        {
          
         try{
          ste = con.createStatement();
          rs = ste.executeQuery(sql);
          cboData.removeAllItems();
          cboData.addItem("Select");
          while(rs.next())
          {
              cboData.addItem(rs.getString(1));
          }
         }
         catch(Exception sqle)
        {
            System.out.println(sqle);
        }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboSearch = new javax.swing.JComboBox<>();
        cboData = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        a.setName(""); // NOI18N

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployee.setName("tblEmployee"); // NOI18N
        a.setViewportView(tblEmployee);

        jLabel1.setText("Search By");

        jLabel2.setText("Select Data");

        cboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Select------", "EmployeeName", "Department", "Post", "Qualification" }));
        cboSearch.setName("cboSearch"); // NOI18N
        cboSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSearchActionPerformed(evt);
            }
        });

        cboData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Select------" }));
        cboData.setName("cboData"); // NOI18N

        btnSearch.setText("Search");
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnShowAll.setText("ShowAll");
        btnShowAll.setName("btnShowAll"); // NOI18N
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(27, 27, 27)
                        .addComponent(btnShowAll)
                        .addGap(0, 257, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnShowAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         if (cboSearch.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(this, "Please select what you want to search by!");
            cboSearch.requestFocus();
            return;
        }
         
          if (cboData.getSelectedIndex() == 0)
        { 
            JOptionPane.showMessageDialog(this, "Please select the data!");
            cboData.requestFocus();
            return;
        }
          
          else
          {
              fillRecord("SELECT * FROM EMPLOYEE WHERE "+ cboSearch.getSelectedItem().toString() + " = '" + cboData.getSelectedItem().toString()+ "'" );
          }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cboSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSearchActionPerformed
        if (cboSearch.getSelectedIndex() >= 0)
        {
            fillSearchData("SELECT DISTINCT "+cboSearch.getSelectedItem().toString()+ " FROM Employee");
            
            
        }
        else
        {
            cboData.addItem("------Select------");
        }
    }//GEN-LAST:event_cboSearchActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        fillRecord("Select * FROM Employee order by EmployeeID");
        cboSearch.setSelectedIndex(0);
        cboData.addItem("------Select------");
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeSearching dialog = new EmployeeSearching(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane a;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JComboBox<String> cboData;
    private javax.swing.JComboBox<String> cboSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable tblEmployee;
    // End of variables declaration//GEN-END:variables
}
