/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeedb;

/**
 *
 * @author User
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuEntry = new javax.swing.JMenuItem();
        mnuUpdate = new javax.swing.JMenuItem();
        mnuSearching = new javax.swing.JMenuItem();
        mnuListing = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:Employee Information System :.");

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");
        jMenu1.setName("mnuFile"); // NOI18N

        mnuEntry.setMnemonic('E');
        mnuEntry.setText("Employee Entry");
        mnuEntry.setName("mnuEntry"); // NOI18N
        mnuEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntryActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEntry);

        mnuUpdate.setMnemonic('U');
        mnuUpdate.setText("Emplyee Update");
        mnuUpdate.setName("mnuUpdate"); // NOI18N
        mnuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUpdateActionPerformed(evt);
            }
        });
        jMenu1.add(mnuUpdate);

        mnuSearching.setText("Employee Searching");
        mnuSearching.setName("mnuSeraching"); // NOI18N
        mnuSearching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSearchingActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSearching);

        mnuListing.setText("Employee Listing");
        mnuListing.setName("mnuListing"); // NOI18N
        mnuListing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListingActionPerformed(evt);
            }
        });
        jMenu1.add(mnuListing);
        jMenu1.add(jSeparator2);

        mnuExit.setText("Exit");
        mnuExit.setName("mnuExit"); // NOI18N
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntryActionPerformed
         EmployeeEntry entry = new EmployeeEntry(this,true);
         entry.show(); 
         
    }//GEN-LAST:event_mnuEntryActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        if(javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure want to exit?", "Exit Program",javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE )== javax.swing.JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUpdateActionPerformed
        EmployeeUpdate update = new EmployeeUpdate(this,true);
        update.show();
    }//GEN-LAST:event_mnuUpdateActionPerformed

    private void mnuSearchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSearchingActionPerformed
        EmployeeSearching search = new EmployeeSearching(this,true);
         search.show();     
    }//GEN-LAST:event_mnuSearchingActionPerformed

    private void mnuListingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListingActionPerformed
        EmployeeListing list = new EmployeeListing(this,true);
        list.show();
    }//GEN-LAST:event_mnuListingActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuEntry;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuListing;
    private javax.swing.JMenuItem mnuSearching;
    private javax.swing.JMenuItem mnuUpdate;
    // End of variables declaration//GEN-END:variables
}
